alias ll='ls -l'
alias la='ls -a'
alias l='ls'
alias e='exit'
alias :q='exit'
alias :Q='exit'
alias ..='cd ..'
alias ga="git add -A"
alias gc="git commit"
alias gp="git push"
alias лс="ls"
alias е="e"
alias цд="cd"
alias so="source ~/.zshrc"
alias zshrc="$EDITOR ~/.zshrc"
alias v="vim"
alias dude="docker compose up -d"
alias dud="docker compose down"
alias aliases="$EDITOR ~/.config/aliasesrc"
alias h=helm
alias hin="helm install"
alias hun="helm uninstall"
alias b='git branch | grep -v "^\*" | fzf --height=20% --reverse --info=inline | xargs git checkout'
alias ed='cursor .'
alias k=kubectl
alias c=clear_and_context
alias t=task_fzf
alias ch=chezmoi
alias ef='fzf --preview "less {}" | xargs cursor'
alias cf='cdf'
